### ISSUE TITLE
Unable to query more than 300 entities after updating to 0.30.0

### ISSUE THREAD

**Issue by mcfarljw** [GoogleCloudPlatform/gcloud-node#1200]
After updating from 0.29.0 to 0.30.0 one of my queries is now capped at returning 300 entities with no cursor. When I revert back to 0.29.0 it properly returns the limit of 1000. Any ideas why this might be happening?

```
var query = datastore.createQuery('Payment')
                        .filter('datemade', '>=', new Date(dateStart))
                        .filter('datemade', '<', new Date(dateEnd))
                        .limit(1000);

datastore.runQuery(
    query,
    function(error, entities, cursor) {
        if (error) {
            console.error(error);
        } else {
            console.log(entities.length);
            console.log(cursor);
        }
    }
);
```

**Comment by stephenplusplus** [comment]
@pcostell [here](https://github.com/GoogleCloudPlatform/gcloud-node/blob/cd0c3e98505c5e29004d063b37a8605b7230a504/lib/datastore/request.js#L458) is our logic for continuing to run queries -- does that look correct?

For reference, [here](https://github.com/GoogleCloudPlatform/gcloud-node/blob/807a61641401e375c72d59b0535eaebe4f8a7e5b/lib/datastore/request.js#L644) is our old logic.

**Comment by stephenplusplus** [comment]
Also @mcfarljw, we don't return a third argument to the callback with `runQuery`, it should just be `error` and `entities`, unless you disable autopagination:

```js
var query = datastore.createQuery('Payment')
                        .filter('datemade', '>=', new Date(dateStart))
                        .filter('datemade', '<', new Date(dateEnd))
                        .limit(1000)
                        .autoPaginate(false);

datastore.runQuery(
    query,
    function(error, entities, nextQuery) {
        if (nextQuery) {
            datastore.runQuery(nextQuery, function(error, entities, nextQuery) {/*...*/});
        }
    }
);
```

**Comment by pcostell** [comment]
@stephenplusplus It looks like your end condition is wrong. It should be "NOT_FINISHED", not "MORE_RESULTS_AFTER_LIMIT"

**Comment by stephenplusplus** [comment]
Thanks! PR and patch incoming @mcfarljw -- thanks for reporting!

**Comment by stephenplusplus** [comment]
Fix is released under v0.30.1 -- please let me know if it works!

**Comment by mcfarljw** [comment]
Thanks for the quick responses! I just loaded up the latest patch v0.30.1, but I'm still not able to all the results that v0.29.0 was returning. _There seems to be something else going on here._

I've done a few more tests directly querying some of my entities with nothing more than a limit of 1000 set. Using v0.29.0 it always returns the requested limit, but when using v0.30.1 it returns a significantly fewer amount they varies based on the entity being queried. For example, the `Payment` entity in the example below will only return up to a limit of 300, if I set it to 301 then the requests seems to go on infinitely without evening timing out. I just tried a simple limit query on another entity and it wouldn't go past a limit of 96.

```
datastore.runQuery(
    datastore.createQuery('Payment').limit(1000),
    function(error, entities) {
        console.log(entities.length);
    }
);
```

**Comment by stephenplusplus** [comment]
I think I've found the problem, but I'll have to take a swing at it tomorrow-- sorry for the delay. I'll send a PR real quick with a rough idea of the solution.

**Comment by stephenplusplus** [comment]
Assuming we fixed it for real this time, it's released in v0.30.2 :)

**Comment by mcfarljw** [comment]
I just tested it out again using `v0.30.2` and was able to query the expected number of entities. Thanks for addressing this in such a timely manner!

**Comment by stephenplusplus** [comment]
Phew! Thank you for reporting it, it was a huge oversight on my part.

:man:
:heavy_minus_sign:
:eyeglasses:
